### ISSUE TITLE
Strange error when using the go-rename plugin...

### ISSUE THREAD

**Issue by svanharmelen** [redefiance/atom-go-rename#3]
This plugin worked before without any issues, but now I get this error on each occasion that I try to rename something:

![image](https://cloud.githubusercontent.com/assets/4171547/7145911/df34e336-e2ef-11e4-90d5-37f20d751f08.png)

While on the commandline it works just fine:

![image](https://cloud.githubusercontent.com/assets/4171547/7145969/6972bec4-e2f0-11e4-8805-598aa38b5f2c.png)

Any clue on how to troubleshoot/fix this?

**Comment by redefiance** [comment]
I can't fathom why it would suddenly stop working when there hasn't been a new version and can't seem to reproduce the error. Are you sure you didn't change anything on your configuration? PATH, settings path of the executable, something like that.

Maybe output the command / args used in go-rename-view.coffee:62 and see if they somehow differ from your input on the command line.

**Comment by svanharmelen** [comment]
Thanks for the pointer, will do some debugging and let you know any findings...

**Comment by dvirsky** [comment]
FWIW It happened to me too, and I solved it by setting PATH, GOPATH and GOROOT in my init script for atom properly.

**Comment by svanharmelen** [comment]
It seems setting the correct path was enough to fix this for me... So my init.coffee now looks like this:

```
process.env.PATH = [
                    "/usr/local/bin",
                    "/usr/bin",
                    "/bin",
                    "/usr/sbin",
                    "/sbin",
                    "/usr/local/go/bin",
                    "/Users/svanharmelen/Documents/GoCode/bin",
                    ].join(":")
```

Thanks @dvirsky for the pointer!

**Comment by dvirsky** [comment]
@svanharmelen yeah I wasn't sure which one did the trick :)
